Hotel_reservations_manager/Hotel_reservations_manager/Models/Shared/PagerViewModel.cs
namespace Hotel_reservations_manager.Models.Shared
{
    public class PagerViewModel
    {
        public int CurrentPage { get; set; }

        public int PagesCount { get; set; }
    }
}

Hotel_reservations_manager/Hotel_reservations_manager/Controllers/AdminsController.cs
using Hotel_reservations_manager.Helpers;
using Hotel_reservations_manager.Models;
using Hotel_reservations_manager.Models.Admins;
using Hotel_reservations_manager.Models.Shared;
using Hotel_reservations_manager.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_reservations_manager.Controllers
{
    public class AdminsController : Controller
    {
        private const int PageSize = 10;
        private readonly HotelContext _context;

        public AdminsController()
        {
            _context = new HotelContext();
        }

        private bool IsUserAuthenticated()
        {
            IAuthenticationHelper authHelper = new SessionAuthenticationHelper(HttpContext.Session);
            return authHelper.IsUserAuthenticated();
        }

        private bool IsAdminAndActive()
        {
            IAuthenticationHelper authHelper = new SessionAuthenticationHelper(HttpContext.Session);
            return authHelper.IsAdminAndActive();
        }

        // GET: List
        public async Task<IActionResult> List(AdminsViewModel model)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/");

            model.Pager ??= new PagerViewModel();
            model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

            List<User> items = _context.Users.Where(e => e.Role == Role.Admin).Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new User()
            {
                Id = c.Id,
                Username = c.Username,
                Password = c.Password,
                FirstName = c.FirstName,
                MiddleName = c.MiddleName,
                LastName = c.LastName,
                PersonalID = c.PersonalID,
                PhoneNumber = c.PhoneNumber,
                Email = c.Email,
                Active = c.Active,
                Role = c.Role
            }).ToList();

            model.Items = items;
            model.Pager.PagesCount = (int)Math.Ceiling(await _context.Rooms.CountAsync() / (double)PageSize);

            return View(model);
        }

        // GET: Admins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/");

            if (id == null)
            {
                return NotFound();
            }

            User admin = await _context.Users.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }

            AdminsEditModel model = new AdminsEditModel
            {
                Id = admin.Id,
                Role = admin.Role,
                Username = admin.Username,
                Password = admin.Password,
                FirstName = admin.FirstName,
                MiddleName = admin.MiddleName,
                LastName = admin.LastName,
                PersonalID = admin.PersonalID,
                PhoneNumber = admin.PhoneNumber,
                Email = admin.Email,
                Active = admin.Active
            };

            return View(model);
        }

        // POST: Admins/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AdminsEditModel model)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/");

            if (ModelState.IsValid)
            {
                User admin = new User
                {
                    Id = model.Id,
                    Username = model.Username,
                    Password = model.Password,
                    FirstName = model.FirstName,
                    MiddleName = model.MiddleName,
                    LastName = model.LastName,
                    PersonalID = model.PersonalID,
                    PhoneNumber = model.PhoneNumber,
                    Email = model.Email,
                    Active = model.Active,
                    Role = model.Role
                };

                try
                {
                    _context.Update(admin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return Redirect("/Admins/List");
            }
                
            return View(model);
        }

        // GET: Admins/Activate/5
        public async Task<IActionResult> Activate(int id)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/");

            User admin = await _context.Users.FindAsync(id);
            if(admin != null)
                admin.Active = true;
            _context.Users.Update(admin);
            await _context.SaveChangesAsync();

            return Redirect("/Admins/List");
        }

        // GET: Admins/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/");

            User admin = await _context.Users.FindAsync(id);
            _context.Users.Remove(admin);
            await _context.SaveChangesAsync();

            return Redirect("/Admins/List");
        }

        private bool AdminExists(int id)
        {
            return _context.Users.Where(e => e.Role == Role.Admin).Any(e => e.Id == id);
        }
    }
}

Hotel_reservations_manager/Hotel_reservations_manager/Controllers/RoomsController.cs
using Hotel_reservations_manager.Helpers;
using Hotel_reservations_manager.Models;
using Hotel_reservations_manager.Models.Rooms;
using Hotel_reservations_manager.Models.Shared;
using Hotel_reservations_manager.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_reservations_manager.Controllers
{
    public class RoomsController : Controller
    {
        private const int PageSize = 10;
        private readonly HotelContext _context;

        public RoomsController()
        {
            _context = new HotelContext();
        }

        private bool IsUserAuthenticated()
        {
            IAuthenticationHelper authHelper = new SessionAuthenticationHelper(HttpContext.Session);
            return authHelper.IsUserAuthenticated();
        }

        private bool IsAdminAndActive()
        {
            IAuthenticationHelper authHelper = new SessionAuthenticationHelper(HttpContext.Session);
            return authHelper.IsAdminAndActive();
        }

        // GET: Rooms
        public async Task<IActionResult> List(RoomsViewModel model)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            bool isAdmin = IsAdminAndActive();
            List<Room> items;

            model.Pager ??= new PagerViewModel();
            model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

            if (isAdmin)
            {
                items = _context.Rooms.Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new Room()
                {
                    Id = c.Id,
                    Number = c.Number,
                    Capacity = c.Capacity,
                    Price = c.Price,
                    Description = c.Description,
                    Type = c.Type,
                    IsFree = c.IsFree
                }).ToList();
            }
            else
            {
                items = _context.Rooms.Where(c => c.IsFree).Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new Room()
                {
                    Id = c.Id,
                    Number = c.Number,
                    Capacity = c.Capacity,
                    Price = c.Price,
                    Description = c.Description,
                    Type = c.Type,
                    IsFree = c.IsFree
                }).ToList();
            }

            model.Items = items;
            model.Pager.PagesCount = (int)Math.Ceiling(await _context.Rooms.CountAsync() / (double)PageSize);
            model.IsAdmin = isAdmin;

            return View(model);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if(!IsAdminAndActive())
                return Redirect("/Rooms/List");

            RoomsCreateModel model = new RoomsCreateModel();

            return View(model);
        }

        // POST: Rooms/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoomsCreateModel model)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/Rooms/List");

            if (ModelState.IsValid)
            {
                Room room = new Room
                {
                    Number = model.Number,
                    Capacity = model.Capacity,
                    Price = model.Price,
                    Description = model.Description,
                    Type = model.Type,
                    IsFree = model.IsFree
                };

                _context.Add(room);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(List));
            }

            return View(model);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/Rooms/List");

            if (id == null)
            {
                return NotFound();
            }

            Room room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            RoomsEditModel model = new RoomsEditModel
            {
                Id = room.Id,
                Number = room.Number,
                Capacity = room.Capacity,
                Price = room.Price,
                Description = room.Description,
                Type = room.Type,
                IsFree = room.IsFree
            };

            return View(model);
        }

        // POST: Rooms/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoomsEditModel model)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/Rooms/List");

            if (ModelState.IsValid)
            {
                Room room = new Room
                {   
                    Id = model.Id,
                    Number = model.Number,
                    Capacity = model.Capacity,
                    Price = model.Price,
                    Description = model.Description,
                    Type = model.Type,
                    IsFree = model.IsFree
                };

                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return Redirect("/Rooms/List");
            }
            return View(model);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            if (!IsAdminAndActive())
                return Redirect("/Rooms/List");

            Room room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();

            return Redirect("/Rooms/List");
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }
    }
}

Hotel_reservations_manager/Hotel_reservations_manager/Controllers/UsersController.cs
using Hotel_reservations_manager.Helpers;
using Hotel_reservations_manager.Models;
using Hotel_reservations_manager.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_reservations_manager.Controllers
{
    public class UsersController : Controller
    {
        private bool IsUserAuthenticated()
        {
            IAuthenticationHelper authHelper = new SessionAuthenticationHelper(HttpContext.Session);
            return authHelper.IsUserAuthenticated();
        }

        private void _logout()
        {
            IAuthenticationHelper authHelper = new SessionAuthenticationHelper(HttpContext.Session);
            authHelper.Logout();
        }

        [HttpGet]
        public IActionResult Register()
        {
            if(IsUserAuthenticated())
                return Redirect("/");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterModel model)
        {
            if (IsUserAuthenticated())
                return Redirect("/");

            if (ModelState.IsValid)
            {
                model.RegisterUser();
                return RedirectToAction("Login");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (IsUserAuthenticated())
                return Redirect("/");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Logout()
        {
            if (!IsUserAuthenticated())
                return Redirect("/Users/Login");

            _logout();
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(LoginModel model)
        {
            if (IsUserAuthenticated())
                return Redirect("/");

            if (ModelState.IsValid)
            {
                var user = model.AuthenticateUser();
                if (user != null)
                {
                    //auth ok, save to session
                    IAuthenticationHelper authHelper = new SessionAuthenticationHelper(HttpContext.Session);
                    authHelper.SaveState(user);
                    return Redirect("/");
                }
                else
                {
                    //add error
                    ModelState.AddModelError(string.Empty, "The username or password provided is incorrect.");
                }
            }
            return View(model);
        }
    }
}

Hotel_reservations_manager/Hotel_reservations_manager/Views/Shared/FormErrors.cshtml
@if (ViewData.ModelState != null && !ViewData.ModelState.IsValid)
{
    <div class="alert-danger">
        <ul>
            @foreach (var state in ViewData.ModelState.Values)
            {
                @foreach (var error in state.Errors)
                {
                    <li>@error.ErrorMessage</li>
                }

            }
        </ul>
    </div>
}

Hotel_reservations_manager/Hotel_reservations_manager/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

Hotel_reservations_manager/Hotel_reservations_manager/Views/Shared/_Layout.cshtml
@using System.Text
@{
    bool auth = false;
    var session = 0;
    var _session = Context.Session;
    byte[] userId = null;
    _session.TryGetValue("userId", out userId);
    if (userId != null && userId.Length > 0)
        auth = true;
    if(auth)
        BitConverter.ToInt32(userId, session);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel reservations manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @Html.Partial("_Favicons")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <img src="/HRMS_logo.png" width="90" height="42">
                <div class="navbar-brand" width="30"></div>
                <a class="navbar-brand" style="padding-bottom:8px;" asp-area="" asp-controller="Home" asp-action="Index">Hotel Reservations</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link nav-link-white" asp-action="Index" asp-controller="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-white" asp-action="List" asp-controller="Reservations">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-white" asp-action="List" asp-controller="Rooms">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-white" asp-action="List" asp-controller="Admins">Admins</a>
                        </li>
                    </ul>
                    @if (auth)
                    {
                        using (Html.BeginForm("Logout", "Users", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-danger">Log out</a>
                            </ul>
                        }
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item">
                                <a class="nav-link nav-link-white" asp-action="Login" asp-controller="Users">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-link-white" asp-action="Register" asp-controller="Users">Register now</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HRMS - Anton Georgiev, Yordan Yordanov and Kristian Petkov
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>